theme: jekyll-theme-slate
title: MRI Together
description: Global workshop on open science and reproducible MR research
email: mritogether@esmrmb.org
twitter: ESMRMB
linkedin: company/esmrmb
youtube: playlist?list=PLeDygc8TN_J48APEUyle4Ql2uSTc74Nsg

google_analytics: G-45HJHW9N5G

repository: mritogether/mritogether.github.io
markdown: kramdown

plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

header:
  links:
    - label: dummy
      url: dummy
    
